baseURL = 'https://swordinboard.com/'
languageCode = 'en-us'
title = 'Sword in Board Workshop'
theme = 'hermit-v2'

enableEmoji = true
enableRobotsTXT = true

[params]
  homeSubtitle = 'A creative space for a not so creative caveman. Welcome to the workshop.'
  homeSubtitlePrinter = true
  # bgImg = none # homepage backgroubd URL
  description = 'Sword in Board Workshop'
  themeColor = '#494f5c'
  readTime = true
  code_copy_button = true
  scrollToTop = true # need scrolltotop: true in page frontmatter
  footerHideThemeName = true
  # pinned = "Pinned Posts" # enables pinned post section on homepage. enable in frontmatter with pin: true
  legacyLayout = false

  [params.author]
    name = 'Anthony'
    about = 'about'

  [[params.socialLinks]]
    name = 'github'
    url = 'https://github.com/swordinboard'

  [[params.socialLinks]]
   name = 'reddit'
   url = 'https://reddit.com/r/theseluckystars/'

  [[params.socialLinks]]
   name = 'email'
   url = 'swordinboard@gmail.com'


[[menu.main]]
  name = 'Blog'
  url = '/posts/'
  weight = 1

[[menu.main]]
  name = 'Projects'
  url = '/projects/'
  weight = 2

[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 3

[taxonomies]
  tag = 'tags'
  
  
# page frontmatter example
# ---
# title: "My First Post"
# date: 2026-02-22
# draft: false
# tags: ["hugo", "web"]
# categories: ["tutorials"]
# featuredImg: "/images/my-image.jpg"
# description: "A short description for meta tags and list views"
# author: "Anthony"
# toc: true
# pin: true
# ---